### PR TITLE
Anchor button

### PR DESCRIPTION
**Pull request by madrus**
I propose a couple of changes.
1. replace anchor with button as using anchor without html tag is not considered as a good practice (both in less and the generated css)
2. use `textOverflow` instead of `text-overflow`
3. fix the snapshot file correspondingly

### CODE REVIEW

**Comment by ndelangen** [comment]
LGTM WDYT @tmeasday ?

**Comment by tmeasday** [comment]
Will need to defer to @domyen on this one

**Comment by domyen** [comment]
This is a great change but can't merge it yet because of this UI regression:
image

Any change you can match the style with what it was before (a lighter shade of grey)

**Comment by johachi** [comment]
Hi!

I was just about to propose the same thing as @madrus .

@domyen @madrus , I would like to propose the following changes to the CSS to fix the star color:

```css
button.link-button {
  background-color: transparent;
  border: none;
  color: #eee; /* will make the star the same color as before */
  cursor: pointer;
  text-decoration: none; /* remove (not changing apparence) */
  display: inline;
  margin: 0;
  padding: 0;

/* Remove 'hover', 'active' and 'focus' below 
(not changing apparence)  */
  &:hover,
  &:active,
  &:focus {
    text-decoration: none;
  }
}
```

Also, I was wondering if this should replace/be squashed into the commit 403f19a and have the [guides](https://github.com/chromaui/learnstorybook.com) to be updated? That would rewrite the history of the repository, which is normally a nono. But I feel that makes sense since this is more a support repository to the guide. (Even though it has been forked over 500 times.)

If you agree, I will happily do such a PR unless Madrus want to do it.

**Comment by madrus** [comment]
@johachi I am not sure what you mean by me doing a PR. I am not very experienced with open source development. This branch here is already a PR branch, right?

**Comment by johachi** [comment]
@madrus no worries. I just meant that I can do a new PR since you have not yet responded to the message by @domyen (changing the color of the star).

Please add `color: #eee;` to the CSS code for `button.link-button` to make the black star grey instead.

Also, remove the `text-decoration` and see if that changes anything of appearance. (I don't think it will since it is the default value for buttons, so it should not be needed, but please double check).

When you have done the changes above simply push to your branch to Github and it should automatically appear in this PR as well.

To change or put this just before previous commits you would have to rebase your branch. Normally rebasing the master branch (or any other branch that several people work on at the same time) can cause a lot of problems and is not anything you would ever do. But I think this repository could be an exception because of the purpose of the repository. Because of that, I would not do it until after @ndelangen and/or @domyen say that they would want it to be done. (There is also a chance they don't want to do it, and then you would have done it for nothing).

**Comment by madrus** [comment]
Ok. I understand. Will get now to try and do as you suggest.

**Comment by madrus** [comment]
Have pushed two commits. In the first one, added LESS/CSS changes as suggested by @johachi. Ran and tested everything. All was OK. 

Then I have noticed that all NPM packages were much outdated, even the storybook itself was in the beta version. So, upgraded and retested everything again, then created a second commit. However, feel free to ignore it if that is not the way it should happen. (upgrading has nothing to do with the anchor button PR).

**Comment by johachi** [comment]
> Then I have noticed that all NPM packages were much outdated, even the storybook itself was in the beta version. So, upgraded and retested everything again, then created a second commit. However, feel free to ignore it if that is not the way it should happen. (upgrading has nothing to do with the anchor button PR).

@madrus many of the packages you updated has already been updated (it is just that you do not have the latest commits in your branch). This causes a branch conflict. Easiest way to fix this conflict is to just drop the commit 10b7f84 and then do a force push to your branch.

If you want to update the the dependencies, you will have to first pull the latest master from this repository (not from your fork) and then update the dependencies.

**Comment by madrus** [comment]
Hi all,
Pulled the latest master from @chromaui, resolved conflicts, pushed my PR
branch, upgraded NPM packages, pushed my PR branch again.
Hope this time it will work.
Greetz,

**Comment by jonniebigodes** [comment]
Closing this as it's currently irrelevant to the code base currently in place.

Stay safe

**Pull request closed without merging**
