### PR TITLE
Angular code

### PR DESCRIPTION
**Pull request by alterx**
I've created the angular version of the code, I'll also submit a PR (that I haven't started to work on just yet) to https://github.com/chromaui/learnstorybook.com to add the angular site in English and Spanish.

What's inside:
- [x] Angular version of the code

What's missing:
- [x] Validate with https://github.com/chromaui/learnstorybook.com/pull/47
- [x] 🚀 

This resolves https://github.com/chromaui/learnstorybook.com/issues/2

### CODE REVIEW

**Comment by tmeasday** [comment]
This is so great! Can't dig through it! Thanks so much @alterx

**Comment by alterx** [comment]
I'm happy to help @tmeasday, I was in the zone so I just kept going 😝 
I've already submitted an initial PR to add the Angular pages, I still need to add the Spanish translations tho

**Comment by tmeasday** [comment]
@alterx this looks perfect! (Except maybe we will make some changes for the data chapter as discussed on the text PR). 

Does it make sense to just have an `angular` branch that consists of this code? In which case I reckon let's just target this PR at that branch and merge there! I will give you access to this repo so you can just rebase etc as you wish. We can get this branch ready directly on the repo and link to it when the text PR is ready.

**Comment by alterx** [comment]
Hey @tmeasday, yeah, I think is does have sense. After all there's a `vue` branch too and the code is vastly different

**Comment by alterx** [comment]
Added the aforementioned changes to the data chapter, this is ready to review and merge @tmeasday

**Comment by tmeasday** [comment]
Great!

**Pull request merged**
